version: 2
jobs:
  ubuntu_gcc_8:
    docker:
      - image: ubuntu:19.04
    steps:
      - run: apt-get update && apt-get install -y git
      - checkout
      - run: apt-get install -y make
      - run: apt-get install -y gcc g++
      - run: make CXX=g++ CXX_STANDARD=c++2a test
  ubuntu_clang_8:
    docker:
      - image: ubuntu:19.04
    steps:
      - run: apt-get update && apt-get install -y git
      - checkout
      - run: apt-get install -y make
      - run: apt-get install -y clang
      - run: make CXX=clang++ CXX_STANDARD=c++2a test
  macos_gcc_8:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: brew install gcc@8
      - run: make CXX=/usr/local/bin/g++-8 CXX_STANDARD=c++2a test
  macos_apple_llvm_10_0:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run: make CXX=clang++ CXX_STANDARD=c++2a test
workflows:
  version: 2
  ci:
    jobs:
      - ubuntu_gcc_8
      - ubuntu_clang_8
      - macos_gcc_8
      - macos_apple_llvm_10_0
